<?php

namespace Paymentree;

define('PAYMENTREE_DEFAULT_LOCAL_IP_ADDRESS', '127.0.0.1');
define('PAYMENTREE_DEFAULT_PORT', 32000);

define('PAYMENTREE_REQUEST_TYPE_PURCHASE', 00);
define('PAYMENTREE_ACTION_TYPE_PURCHASE', 00);

define('PAYMENTREE_REQUEST_TYPE_REFUND', 00);
define('PAYMENTREE_ACTION_TYPE_REFUND', 10);

define('PAYMENTREE_REQUEST_TYPE_VOID', 00);
define('PAYMENTREE_ACTION_TYPE_VOID', 30);

define('PAYMENTREE_REQUEST_TYPE_QUERY_VOID', 00);
define('PAYMENTREE_ACTION_TYPE_QUERY_VOID', 22);

define('PAYMENTREE_REQUEST_TYPE_COMMIT', 00);
define('PAYMENTREE_ACTION_TYPE_COMMIT', 40);

define('PAYMENTREE_REQUEST_TYPE_TERMINAL_CLOSE_LIST', 00);
define('PAYMENTREE_ACTION_TYPE_TERMINAL_CLOSE_LIST', 28);

define('PAYMENTREE_REQUEST_TYPE_TERMINAL_CLOSE', 00);
define('PAYMENTREE_ACTION_TYPE_TERMINAL_CLOSE', 51);

class Paymentree {
  /**
   * @var string
   */
  public static $DEFAULT_LOCAL_IP_ADDRESS = '127.0.0.1';

  /**
   * @var int
   */
  public static $DEFAULT_PORT = 320000;
}
